# File: app/traefik-install-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-install
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-traefik
  source:
    repoURL: https://github.com/bioyeneye/homelab-network.git
    targetRevision: HEAD
    path: internal-traefik/base
    helm:
      chart: traefik
      repoURL: https://helm.traefik.io/traefik
      version: 23.2.0
      valueFiles:
        - traefik-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true