apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/kustomize-enable-helm: "true"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-traefik
  source:
    repoURL: https://github.com/bioyeneye/homelab-network.git
    targetRevision: HEAD
    path: internal-traefik/base
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Replace=true
      - Validate=false
      - AllowEmpty=true
      - EnableHelm=true
