apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-install
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-traefik
  source:
    repoURL: https://github.com/bioyeneye/homelab-network.git
    targetRevision: HEAD
    path: internal-traefik/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m