# File: traefik/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-traefik

# Reference the Traefik Helm chart directly
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts  # Correct official repo
    version: 26.0.0  # Updated to latest stable version
    releaseName: traefik-install
    namespace: internal-traefik
    valuesFile: traefik-values.yaml
    includeCRDs: true  # Important for Traefik CRDs

# Resources to add/overlay on top of the Helm chart
resources:
  - dashboard  # Correct relative path to dashboard folder

commonLabels:
  app.kubernetes.io/name: traefik
  app.kubernetes.io/instance: traefik-install
  app.kubernetes.io/component: ingress-controller]