apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/bioyeneye/homelab-network.git       # ✅ Your Git repo
    targetRevision: HEAD                                          # ✅ or specify a branch/tag
    path: internal-traefik/base                                   # ✅ Folder where values.yaml is
    helm:
      chart: traefik                                              # ✅ The Helm chart name
      repo: https://helm.traefik.io/traefik                       # ✅ Helm chart repo
      version: 23.2.0                                             # ✅ Chart version
      valueFiles:
        - traefik-values.yaml                                     # ✅ Your custom values file
  destination:
    server: https://kubernetes.default.svc                        # ✅ Your in-cluster target
    namespace: internal-traefik                                   # ✅ Namespace to install into
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
