apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: internal-traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dashboard.internal.local`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService