apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: internal-traefik
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.230
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443