deployment:
  enabled: true
  replicas: 2

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.1.230
  annotations: {}

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    protocol: TCP

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
