apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 23.2.0
    helm:
      valueFiles:
        - traefik-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true