# File: traefik/base/traefik-values.yaml
# Traefik Helm Chart Values - Internal Configuration (No Let's Encrypt)

# Deployment Configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 2  # For high availability

# Image Configuration
image:
  name: traefik
  tag: "v3.0.4"  # Latest stable version
  pullPolicy: IfNotPresent

# Entry Points Configuration - HTTP Only for Internal Use
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    # No HTTPS redirect for internal use
  traefik:
    port: 9000
    expose: false  # Dashboard port - not exposed externally

# Entry Points (simplified for internal use)
entryPoints:
  web:
    address: ":8000"
  # No websecure entry point needed for internal

# Providers Configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

# Service Configuration with MetalLB
service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.231"  # Your IP
    metallb.universe.tf/allow-shared-ip: "traefik-svc"
  spec:
    externalTrafficPolicy: Local  # Better for MetalLB

# Additional Arguments - Simplified for Internal
additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=false"  # Keep API secure even internally
  - "--log.level=INFO"
  - "--accesslog=true"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.addEntryPointsLabels=true"
  - "--metrics.prometheus.addServicesLabels=true"
  - "--ping=true"
  # No Let's Encrypt configuration needed

# Security Context (Fixed)
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: OnRootMismatch

# Resource Management
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Health Checks
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

# RBAC
rbac:
  enabled: true
  namespaced: false

# Service Account
serviceAccount:
  create: true

# Ingress Class
ingressClass:
  enabled: true
  isDefaultClass: true

# No persistence needed without Let's Encrypt
# persistence:
#   enabled: false

# Node Selection and Anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname