apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 24.0.0
    releaseName: internal-traefik
    namespace: kube-system
    valuesFile: values.yaml
