apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 23.2.0
    releaseName: traefik-install
    namespace: internal-traefik
    valuesFile: traefik-values.yaml

namespace: internal-traefik