additionalArguments:
  - "--api.dashboard=true"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetescrd"
  - "--accesslog=true"
  - "--log.level=INFO"
  - "--metrics.prometheus=true"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231
  ports:
    web:
      port: 80
    websecure:
      port: 443

securityContext:
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false