deployment:
  enabled: true
  replicas: 2

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.1.230
  annotations: {}

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP

entryPoints:
  web:
    address: ":8000"
  websecure:
    address: ":8443"

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

logs:
  general:
    level: DEBUG